name: "Promote to prod"

on:
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [published]

jobs:
  update-k8s-manifest:
    name: Update k8s manifest with release version
    runs-on: ubuntu-latest
    steps:
      # This workflow assumes that the GITHUB_SHA that triggered this action already has a Docker image tagged
      # in the Container Registry (presumably put there by the 'merge-to-main.yml' workflow)
      - name: Get short-sha
        id: shortsha
        run: echo "::set-output name=shortsha::$(echo $GITHUB_SHA | head -c7)"

      # Uses credentials from the evanhsu/AuthBot Github App (https://github.com/settings/installations/28169783)
      - id: deploy-pat
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.AUTHBOT_APP_ID }}
          private_key: ${{ secrets.AUTHBOT_PRIVATE_KEY }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      # This step will exit with an error if there's no active garbage collection in progress.
      # So we'll need to continue-on-error to handle that scenario.
      - name: Check for an active garbage collection process in the container registry
        id: active-garbage-collection
        continue-on-error: true
        run: |
          GC=$(doctl registry garbage-collection get-active --format UUID,RegistryName,Status --output json)
          echo "::set-output name=uuid::$(echo $GC | jq -r '.[0].uuid')"
          echo "Found active garbage collection in progress: $GC"

      # The DigitalOcean container registry is read-only during garbage collection, which can last 15 minutes or so.
      # We need to cancel the current garbage collection process so that we can push the new image tag
      - name: Cancel any active garbage collection in the container registry
        if: steps.active-garbage-collection.outputs.uuid != ''
        run: |
          doctl registry garbage-collection cancel ${{ steps.active-garbage-collection.outputs.uuid }}
          sleep 10s

      - name: Update image tag in k8s deployment repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update image tag
          repo: evanhsu/smirksoftware-k8s
          # Always trigger the target workflow on the main branch of the target repo
          ref: main
          token: ${{ steps.deploy-pat.outputs.token }}
          inputs: '{ "app": "firecrew", "environment": "prod", "image": "firecrew/firecrew-app", "tag": "${{ steps.shortsha.outputs.shortsha }}"}'

      - name: Add 'prod' tag to the docker image in the container registry
        run: |
          docker pull registry.digitalocean.com/firecrew/firecrew-app:${{ steps.shortsha.outputs.shortsha }}
          docker tag registry.digitalocean.com/firecrew/firecrew-app:${{ steps.shortsha.outputs.shortsha }} registry.digitalocean.com/firecrew/firecrew-app:prod
          docker push registry.digitalocean.com/firecrew/firecrew-app:prod
